"""empty message

Revision ID: 214f4cc6f0a1
Revises: d01effdc44ed
Create Date: 2022-11-03 10:29:06.590036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '214f4cc6f0a1'
down_revision = 'd01effdc44ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('exam_rank', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'exam_rank')
    # ### end Alembic commands ###
