"""empty message

Revision ID: d01effdc44ed
Revises: fc607e4c8676
Create Date: 2022-11-03 10:19:33.112337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd01effdc44ed'
down_revision = 'fc607e4c8676'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('land',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('land_doc', sa.String(), nullable=True),
    sa.Column('land_area', sa.Integer(), nullable=True),
    sa.Column('land_pincode', sa.Integer(), nullable=True),
    sa.Column('land_district', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('land')
    # ### end Alembic commands ###
